language: node_js
node_js:
  - "10"
cache: yarn
git:
  depth: 3
jobs:
  include:
    - script: cp ./config/config.dev.json.example ./config/config.dev.json
    - script: yarn lint
    - script: yarn test
    - script: yarn build
